/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Status */
        get: operations["auth_status_api_auth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth Setup */
        post: operations["auth_setup_api_auth_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth Login */
        post: operations["auth_login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth Logout */
        post: operations["auth_logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Me */
        get: operations["auth_me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth Change Password */
        post: operations["auth_change_password_api_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Media */
        get: operations["list_media_api_media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trash */
        get: operations["list_trash_api_media_trash_get"];
        put?: never;
        post?: never;
        /** Empty Trash */
        delete: operations["empty_trash_api_media_trash_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/duplicates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Duplicates
         * @description Return clusters of media that share the same file_hash.
         *
         *     Implementation: 1 GROUP BY query to find candidate hashes + 1 bulk fetch
         *     of all media in those hashes + 1 bulk fetch of metadata. No N+1.
         */
        get: operations["list_duplicates_api_media_duplicates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Media Detail */
        get: operations["get_media_detail_api_media__media_id__get"];
        put?: never;
        post?: never;
        /** Delete Media */
        delete: operations["delete_media_api_media__media_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{media_id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thumbnail File */
        get: operations["get_thumbnail_file_api_media__media_id__thumbnail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{media_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preview Image */
        get: operations["get_preview_image_api_media__media_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{media_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Media File */
        get: operations["get_media_file_api_media__media_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{media_id}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Media Rating */
        put: operations["set_media_rating_api_media__media_id__rating_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{media_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Media Tags */
        post: operations["add_media_tags_api_media__media_id__tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{media_id}/tags/{tag_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Media Tag */
        delete: operations["remove_media_tag_api_media__media_id__tags__tag_name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{media_id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Media Metadata */
        patch: operations["update_media_metadata_api_media__media_id__metadata_patch"];
        trace?: never;
    };
    "/api/media/{media_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Media */
        post: operations["restore_media_api_media__media_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_api_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Rename Tag */
        put: operations["rename_tag_api_tags__tag_id__put"];
        post?: never;
        /** Delete Tag */
        delete: operations["delete_tag_api_tags__tag_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Timeline */
        get: operations["get_timeline_api_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cameras */
        get: operations["get_cameras_api_cameras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Random Media */
        get: operations["get_random_media_api_random_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Geo
         * @description Return up to `limit` GPS-tagged media as compact map markers — single
         *     JOIN query, no pagination needed. Frontend Map view uses this.
         */
        get: operations["get_geo_api_geo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch Add Tags */
        post: operations["batch_add_tags_api_batch_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch/tags/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch Remove Tags */
        post: operations["batch_remove_tags_api_batch_tags_remove_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch Set Rating */
        post: operations["batch_set_rating_api_batch_rating_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch Delete */
        post: operations["batch_delete_api_batch_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch Update Metadata
         * @description Apply the same metadata patch (date/gps/location) to many media.
         */
        post: operations["batch_update_metadata_api_batch_metadata_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Albums */
        get: operations["list_albums_api_albums_get"];
        put?: never;
        /** Create Album */
        post: operations["create_album_api_albums_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/albums/{album_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Album */
        delete: operations["delete_album_api_albums__album_id__delete"];
        options?: never;
        head?: never;
        /** Rename Album */
        patch: operations["rename_album_api_albums__album_id__patch"];
        trace?: never;
    };
    "/api/albums/{album_id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Media To Album */
        post: operations["add_media_to_album_api_albums__album_id__media_post"];
        /** Remove Media From Album */
        delete: operations["remove_media_from_album_api_albums__album_id__media_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/smart-albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Smart Albums
         * @description Return all smart album sections with covers resolved server-side.
         */
        get: operations["get_smart_albums_api_smart_albums_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/smart-albums/definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Definitions
         * @description Return all smart album definitions (including disabled) for admin.
         */
        get: operations["list_definitions_api_smart_albums_definitions_get"];
        put?: never;
        /**
         * Create Definition
         * @description Create a new smart album definition (user-created, is_system=0).
         */
        post: operations["create_definition_api_smart_albums_definitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/smart-albums/definitions/{album_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Definition */
        get: operations["get_definition_api_smart_albums_definitions__album_id__get"];
        /**
         * Update Definition
         * @description Update an existing smart album definition.
         */
        put: operations["update_definition_api_smart_albums_definitions__album_id__put"];
        post?: never;
        /**
         * Delete Definition
         * @description Delete a non-system smart album definition.
         */
        delete: operations["delete_definition_api_smart_albums_definitions__album_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/smart-albums/definitions/{album_id}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Toggle Definition
         * @description Toggle enabled/disabled state of a smart album definition.
         */
        patch: operations["toggle_definition_api_smart_albums_definitions__album_id__toggle_patch"];
        trace?: never;
    };
    "/api/smart-albums/definitions/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Definitions
         * @description Delete all smart album definitions and re-seed defaults.
         */
        post: operations["reset_definitions_api_smart_albums_definitions_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Library
         * @description Return info about the currently active library.
         */
        get: operations["get_current_library_api_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recent Libraries
         * @description Return the list of recently used library paths.
         */
        get: operations["list_recent_libraries_api_library_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Switch Library
         * @description Switch the active library database.
         */
        post: operations["switch_library_api_library_switch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Library Config
         * @description Return all library config key-value pairs.
         */
        get: operations["get_library_config_api_library_config_get"];
        /**
         * Update Library Config
         * @description Update one or more library config keys.
         */
        put: operations["update_library_config_api_library_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlbumActionResponse
         * @description Acknowledgement for add/remove-media album mutations.
         */
        AlbumActionResponse: {
            /** Message */
            message: string;
            /** Affected */
            affected: number;
        };
        /** AlbumMediaBody */
        AlbumMediaBody: {
            /** Media Ids */
            media_ids: number[];
        };
        /**
         * AlbumSummary
         * @description Summary returned by GET /api/albums.
         */
        AlbumSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Cover Media Id */
            cover_media_id?: number | null;
            /**
             * Count
             * @default 0
             */
            count: number;
            /** Created At */
            created_at?: string | null;
        };
        /** AuthStatus */
        AuthStatus: {
            /** Setup Required */
            setup_required: boolean;
        };
        /**
         * BatchAffected
         * @description Server reports how many items were actually mutated by a batch op.
         */
        BatchAffected: {
            /** Affected */
            affected: number;
        };
        /** BatchDeleteBody */
        BatchDeleteBody: {
            /** Media Ids */
            media_ids: number[];
        };
        /**
         * BatchMetadataBody
         * @description Bulk-apply the same metadata patch to many media.
         */
        BatchMetadataBody: {
            /** Media Ids */
            media_ids: number[];
            /** Date Taken */
            date_taken?: string | null;
            /** Gps Lat */
            gps_lat?: number | null;
            /** Gps Lon */
            gps_lon?: number | null;
            /** Location Label */
            location_label?: string | null;
            /** Location City */
            location_city?: string | null;
            /** Location Country */
            location_country?: string | null;
        };
        /** BatchRatingBody */
        BatchRatingBody: {
            /** Media Ids */
            media_ids: number[];
            /** Rating */
            rating: number;
        };
        /** BatchTagBody */
        BatchTagBody: {
            /** Media Ids */
            media_ids: number[];
            /** Tags */
            tags: string[];
        };
        /** BatchTagRemoveBody */
        BatchTagRemoveBody: {
            /** Media Ids */
            media_ids: number[];
            /** Tags */
            tags: string[];
        };
        /** CameraStats */
        CameraStats: {
            /** Make */
            make: string;
            /** Model */
            model: string;
            /** Count */
            count: number;
        };
        /** ChangePasswordBody */
        ChangePasswordBody: {
            /** Old Password */
            old_password: string;
            /** New Password */
            new_password: string;
        };
        /** CreateAlbumBody */
        CreateAlbumBody: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** CreateUserBody */
        CreateUserBody: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
        };
        /**
         * CreatedAlbum
         * @description Mirrors what AlbumsApi.create returns — same shape as AlbumSummary.
         */
        CreatedAlbum: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Cover Media Id */
            cover_media_id?: number | null;
            /**
             * Count
             * @default 0
             */
            count: number;
            /** Created At */
            created_at?: string | null;
        };
        /**
         * DuplicateGroup
         * @description Cluster of media that share the same file_hash.
         */
        DuplicateGroup: {
            /** File Hash */
            file_hash: string;
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["MediaBrief"][];
        };
        /**
         * GeoPoint
         * @description Compact map marker payload — `/api/geo` returns this in bulk.
         */
        GeoPoint: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /** Media Type */
            media_type: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Date */
            date?: string | null;
            /** City */
            city?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LibraryInfo */
        LibraryInfo: {
            /** Db Path */
            db_path: string;
            /** Name */
            name: string;
            /** Library Id */
            library_id?: string | null;
        };
        /** LibraryStats */
        LibraryStats: {
            /** Total Files */
            total_files: number;
            /** Total Size */
            total_size: number;
            type_distribution: components["schemas"]["TypeDistribution"];
            /** Tags */
            tags: components["schemas"]["TagStats"][];
            /** Cameras */
            cameras: components["schemas"]["CameraStats"][];
        };
        /** LoginBody */
        LoginBody: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Token */
            token: string;
            user: components["schemas"]["UserSummary"];
        };
        /**
         * MediaBrief
         * @description Lightweight media row used in list views (grid pagination).
         */
        MediaBrief: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /** Extension */
            extension: string;
            /** Media Type */
            media_type: string;
            /** File Size */
            file_size: number;
            /** Rating */
            rating: number;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** Date Taken */
            date_taken?: string | null;
            /** Camera Model */
            camera_model?: string | null;
            /** Duration */
            duration?: number | null;
            /** Gps Lat */
            gps_lat?: number | null;
            /** Gps Lon */
            gps_lon?: number | null;
            /** Location Label */
            location_label?: string | null;
            /** Location City */
            location_city?: string | null;
            /** Location Country */
            location_country?: string | null;
            /** Deleted At */
            deleted_at?: string | null;
        };
        /**
         * MediaDetail
         * @description Full media detail with metadata + tags (used by viewer/info panel).
         */
        MediaDetail: {
            /** Id */
            id: number;
            /** Path */
            path: string;
            /** Filename */
            filename: string;
            /** Extension */
            extension: string;
            /** Media Type */
            media_type: string;
            /** File Size */
            file_size: number;
            /** File Hash */
            file_hash: string;
            /** Rating */
            rating: number;
            /** Scanned At */
            scanned_at?: string | null;
            metadata?: components["schemas"]["MediaMetadata"] | null;
            /**
             * Tags
             * @default []
             */
            tags: components["schemas"]["MediaTag"][];
        };
        /**
         * MediaMetadata
         * @description Full per-item EXIF/derived metadata payload.
         */
        MediaMetadata: {
            /** Date Taken */
            date_taken?: string | null;
            /** Camera Make */
            camera_make?: string | null;
            /** Camera Model */
            camera_model?: string | null;
            /** Lens Model */
            lens_model?: string | null;
            /** Focal Length */
            focal_length?: number | null;
            /** Aperture */
            aperture?: number | null;
            /** Shutter Speed */
            shutter_speed?: string | null;
            /** Iso */
            iso?: number | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** Duration */
            duration?: number | null;
            /** Gps Lat */
            gps_lat?: number | null;
            /** Gps Lon */
            gps_lon?: number | null;
            /** Orientation */
            orientation?: number | null;
            /** Location Label */
            location_label?: string | null;
            /** Location Country */
            location_country?: string | null;
            /** Location City */
            location_city?: string | null;
        };
        /** MediaTag */
        MediaTag: {
            /** Name */
            name: string;
            /** Source */
            source: string;
            /** Confidence */
            confidence?: number | null;
        };
        /** PaginatedMedia */
        PaginatedMedia: {
            /** Items */
            items: components["schemas"]["MediaBrief"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Pages */
            pages: number;
        };
        /** RatingBody */
        RatingBody: {
            /** Rating */
            rating: number;
        };
        /** RatingResponse */
        RatingResponse: {
            /** Rating */
            rating: number;
        };
        /** RenameTagBody */
        RenameTagBody: {
            /** Name */
            name: string;
        };
        /** SetupBody */
        SetupBody: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
        };
        /**
         * SmartAlbumBody
         * @description Create or update a smart album definition.
         */
        SmartAlbumBody: {
            /** Key */
            key: string;
            /**
             * Section
             * @default custom
             */
            section: string;
            /** Title */
            title: string;
            /**
             * Subtitle
             * @default
             */
            subtitle: string;
            /**
             * Icon
             * @default images
             */
            icon: string;
            /**
             * Color
             * @default
             */
            color: string;
            /**
             * Filters
             * @default {}
             */
            filters: {
                [key: string]: unknown;
            };
            /** Generator */
            generator?: string | null;
            /**
             * Generator Config
             * @default {}
             */
            generator_config: {
                [key: string]: unknown;
            };
            /**
             * Position
             * @default 0
             */
            position: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /**
         * SmartAlbumDefinition
         * @description Raw smart-album definition row used by admin CRUD endpoints.
         */
        SmartAlbumDefinition: {
            /** Id */
            id: number;
            /** Key */
            key: string;
            /**
             * Section
             * @default custom
             */
            section: string;
            /** Title */
            title: string;
            /**
             * Subtitle
             * @default
             */
            subtitle: string;
            /**
             * Icon
             * @default images
             */
            icon: string;
            /**
             * Color
             * @default
             */
            color: string;
            /** Filters */
            filters?: {
                [key: string]: unknown;
            };
            /** Generator */
            generator?: string | null;
            /** Generator Config */
            generator_config?: {
                [key: string]: unknown;
            };
            /**
             * Position
             * @default 0
             */
            position: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Is System
             * @default 0
             */
            is_system: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * SmartAlbumEntry
         * @description One smart-album manifest as exposed by /api/smart-albums.
         */
        SmartAlbumEntry: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            /**
             * Subtitle
             * @default
             */
            subtitle: string;
            /** Count */
            count?: number | null;
            /** Cover Id */
            cover_id?: number | null;
            /** Icon */
            icon?: string | null;
            /**
             * Color
             * @default
             */
            color: string;
            /** Filters */
            filters?: {
                [key: string]: unknown;
            };
            /** Search Text */
            search_text?: string | null;
            /** Festival Id */
            festival_id?: string | null;
        };
        /** SmartAlbumResetResult */
        SmartAlbumResetResult: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Seeded */
            seeded: number;
        };
        /**
         * SmartAlbumUpdateBody
         * @description Partial update for an existing smart album definition.
         */
        SmartAlbumUpdateBody: {
            /** Key */
            key?: string | null;
            /** Section */
            section?: string | null;
            /** Title */
            title?: string | null;
            /** Subtitle */
            subtitle?: string | null;
            /** Icon */
            icon?: string | null;
            /** Color */
            color?: string | null;
            /** Filters */
            filters?: {
                [key: string]: unknown;
            } | null;
            /** Generator */
            generator?: string | null;
            /** Generator Config */
            generator_config?: {
                [key: string]: unknown;
            } | null;
            /** Position */
            position?: number | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /** SmartAlbumsResponse */
        SmartAlbumsResponse: {
            /**
             * Library
             * @default []
             */
            library: components["schemas"]["SmartAlbumEntry"][];
            /**
             * Tags
             * @default []
             */
            tags: components["schemas"]["SmartAlbumEntry"][];
            /**
             * Cameras
             * @default []
             */
            cameras: components["schemas"]["SmartAlbumEntry"][];
            /**
             * Festivals
             * @default []
             */
            festivals: components["schemas"]["SmartAlbumEntry"][];
            /**
             * Years
             * @default []
             */
            years: components["schemas"]["SmartAlbumEntry"][];
            /**
             * Places
             * @default []
             */
            places: components["schemas"]["SmartAlbumEntry"][];
        };
        /**
         * StatusMessage
         * @description Generic acknowledgement payload.
         */
        StatusMessage: {
            /** Message */
            message: string;
        };
        /**
         * StatusOk
         * @description Acknowledgement payload using `status: "ok"` shape.
         */
        StatusOk: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /**
         * SwitchLibraryBody
         * @description Request body for switching the active library database.
         */
        SwitchLibraryBody: {
            /** Db Path */
            db_path: string;
        };
        /** SwitchLibraryResponse */
        SwitchLibraryResponse: {
            /** Db Path */
            db_path: string;
            /** Name */
            name: string;
            /** Message */
            message: string;
        };
        /** TagStats */
        TagStats: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Count */
            count: number;
        };
        /** TagsBody */
        TagsBody: {
            /** Tags */
            tags: string[];
        };
        /**
         * TimelineEntry
         * @description One bucket in the timeline distribution (year-month or year).
         */
        TimelineEntry: {
            /** Period */
            period: string;
            /** Count */
            count: number;
        } & {
            [key: string]: unknown;
        };
        /** TypeDistribution */
        TypeDistribution: {
            /**
             * Photo
             * @default 0
             */
            photo: number;
            /**
             * Video
             * @default 0
             */
            video: number;
            /**
             * Audio
             * @default 0
             */
            audio: number;
        };
        /** UpdateMetadataBody */
        UpdateMetadataBody: {
            /** Date Taken */
            date_taken?: string | null;
            /** Gps Lat */
            gps_lat?: number | null;
            /** Gps Lon */
            gps_lon?: number | null;
            /** Location Label */
            location_label?: string | null;
            /** Location City */
            location_city?: string | null;
            /** Location Country */
            location_country?: string | null;
            /** Camera Make */
            camera_make?: string | null;
            /** Camera Model */
            camera_model?: string | null;
            /** Lens Model */
            lens_model?: string | null;
            /** Aperture */
            aperture?: number | null;
            /** Shutter Speed */
            shutter_speed?: string | null;
            /** Iso */
            iso?: number | null;
            /** Focal Length */
            focal_length?: number | null;
        };
        /**
         * UserDetail
         * @description List view payload returned by `GET /api/users`.
         */
        UserDetail: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Is Admin */
            is_admin: boolean;
            /** Created At */
            created_at?: string | null;
        };
        /** UserSummary */
        UserSummary: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Is Admin */
            is_admin: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_status_api_auth_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatus"];
                };
            };
        };
    };
    auth_setup_api_auth_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusMessage"];
                };
            };
        };
    };
    auth_me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
        };
    };
    auth_change_password_api_auth_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetail"][];
                };
            };
        };
    };
    create_user_api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOk"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_media_api_media_get: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                type?: string | null;
                tag?: string | null;
                camera?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                date_ranges?: string | null;
                sort?: string;
                order?: string;
                search?: string | null;
                min_rating?: number | null;
                favorites_only?: boolean;
                lat?: number | null;
                lon?: number | null;
                radius?: number | null;
                has_location?: boolean;
                no_date?: boolean;
                deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMedia"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trash_api_media_trash_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaBrief"][];
                };
            };
        };
    };
    empty_trash_api_media_trash_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusMessage"];
                };
            };
        };
    };
    list_duplicates_api_media_duplicates_get: {
        parameters: {
            query?: {
                min_count?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateGroup"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_detail_api_media__media_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_media_api_media__media_id__delete: {
        parameters: {
            query?: {
                /** @description Permanently delete instead of trash */
                permanent?: boolean;
                /** @description Also delete the file from disk */
                delete_file?: boolean;
            };
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thumbnail_file_api_media__media_id__thumbnail_get: {
        parameters: {
            query?: {
                size?: string;
            };
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preview_image_api_media__media_id__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_file_api_media__media_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_media_rating_api_media__media_id__rating_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_media_tags_api_media__media_id__tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_media_tag_api_media__media_id__tags__tag_name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
                tag_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_media_metadata_api_media__media_id__metadata_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMetadataBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_media_api_media__media_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagStats"][];
                };
            };
        };
    };
    rename_tag_api_tags__tag_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameTagBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOk"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tag_api_tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOk"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryStats"];
                };
            };
        };
    };
    get_timeline_api_timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEntry"][];
                };
            };
        };
    };
    get_cameras_api_cameras_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraStats"][];
                };
            };
        };
    };
    get_random_media_api_random_get: {
        parameters: {
            query?: {
                count?: number;
                type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaBrief"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_geo_api_geo_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_add_tags_api_batch_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchTagBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchAffected"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_remove_tags_api_batch_tags_remove_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchTagRemoveBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchAffected"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_set_rating_api_batch_rating_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRatingBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchAffected"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_delete_api_batch_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchDeleteBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchAffected"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_update_metadata_api_batch_metadata_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchMetadataBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchAffected"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_albums_api_albums_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumSummary"][];
                };
            };
        };
    };
    create_album_api_albums_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAlbumBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedAlbum"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_album_api_albums__album_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                album_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_album_api_albums__album_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                album_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAlbumBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusMessage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_media_to_album_api_albums__album_id__media_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                album_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlbumMediaBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_media_from_album_api_albums__album_id__media_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                album_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlbumMediaBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_smart_albums_api_smart_albums_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmartAlbumsResponse"];
                };
            };
        };
    };
    list_definitions_api_smart_albums_definitions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmartAlbumDefinition"][];
                };
            };
        };
    };
    create_definition_api_smart_albums_definitions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmartAlbumBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmartAlbumDefinition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_definition_api_smart_albums_definitions__album_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                album_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmartAlbumDefinition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_definition_api_smart_albums_definitions__album_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                album_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmartAlbumUpdateBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmartAlbumDefinition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_definition_api_smart_albums_definitions__album_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                album_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOk"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_definition_api_smart_albums_definitions__album_id__toggle_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                album_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmartAlbumDefinition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_definitions_api_smart_albums_definitions_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmartAlbumResetResult"];
                };
            };
        };
    };
    get_current_library_api_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryInfo"];
                };
            };
        };
    };
    list_recent_libraries_api_library_recent_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryInfo"][];
                };
            };
        };
    };
    switch_library_api_library_switch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchLibraryBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwitchLibraryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_library_config_api_library_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    update_library_config_api_library_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
