"""Default smart album seed data."""

from __future__ import annotations

from typing import Any

DEFAULT_SMART_ALBUMS: list[dict[str, Any]] = [
    # ── Library section (static) ──
    {
        "key": "all",
        "section": "library",
        "title": "All Media",
        "icon": "images",
        "filters": {"sort": "date_taken", "order": "desc"},
        "position": 0,
    },
    {
        "key": "photos",
        "section": "library",
        "title": "Photos",
        "icon": "image",
        "filters": {"type": "photo", "sort": "date_taken", "order": "desc"},
        "position": 1,
    },
    {
        "key": "videos",
        "section": "library",
        "title": "Videos",
        "icon": "film",
        "filters": {"type": "video", "sort": "date_taken", "order": "desc"},
        "position": 2,
    },
    {
        "key": "favorites",
        "section": "library",
        "title": "Favorites",
        "subtitle": "★4 and above",
        "icon": "star",
        "color": "bg-amber-500/5",
        "filters": {"min_rating": 4, "sort": "rating", "order": "desc"},
        "position": 3,
    },
    {
        "key": "trash",
        "section": "library",
        "title": "Recently Deleted",
        "icon": "trash-2",
        "color": "bg-destructive/5",
        "filters": {"deleted": True, "sort": "date_taken", "order": "desc"},
        "position": 4,
    },
    # ── Generators ──
    {
        "key": "gen:tags",
        "section": "tags",
        "title": "Tags",
        "icon": "tag",
        "color": "bg-violet-500/5",
        "generator": "per_tag",
        "position": 0,
    },
    {
        "key": "gen:cameras",
        "section": "cameras",
        "title": "Cameras",
        "icon": "camera",
        "generator": "per_camera",
        "position": 0,
    },
    {
        "key": "gen:years",
        "section": "years",
        "title": "Years",
        "icon": "calendar",
        "generator": "per_year",
        "position": 0,
    },
    {
        "key": "gen:festivals",
        "section": "festivals",
        "title": "Festivals",
        "icon": "sparkles",
        "color": "bg-red-500/5",
        "generator": "per_festival",
        "generator_config": {
            "festivals": [
                {
                    "id": "spring",
                    "name": "春节",
                    "emoji": "🧧",
                    "search": "spring festival chinese new year 过年 新年 除夕",
                    "lunar_month": 1,
                    "lunar_day": 1,
                    "days_before": 1,
                    "days_after": 6,
                },
                {
                    "id": "lantern",
                    "name": "元宵节",
                    "emoji": "🏮",
                    "search": "lantern festival 元宵 汤圆 花灯",
                    "lunar_month": 1,
                    "lunar_day": 15,
                    "days_before": 0,
                    "days_after": 0,
                },
                {
                    "id": "qingming",
                    "name": "清明节",
                    "emoji": "🌿",
                    "search": "qingming tomb sweeping 清明 踏青 扫墓",
                    "solar_term": True,
                    "days_before": 0,
                    "days_after": 2,
                },
                {
                    "id": "dragon",
                    "name": "端午节",
                    "emoji": "🐉",
                    "search": "dragon boat festival 端午 粽子 龙舟",
                    "lunar_month": 5,
                    "lunar_day": 5,
                    "days_before": 0,
                    "days_after": 2,
                },
                {
                    "id": "qixi",
                    "name": "七夕",
                    "emoji": "🎋",
                    "search": "qixi chinese valentine 七夕 情人节 牛郎织女",
                    "lunar_month": 7,
                    "lunar_day": 7,
                    "days_before": 0,
                    "days_after": 0,
                },
                {
                    "id": "midautumn",
                    "name": "中秋节",
                    "emoji": "🥮",
                    "search": "mid autumn moon festival 中秋 月饼 赏月 团圆",
                    "lunar_month": 8,
                    "lunar_day": 15,
                    "days_before": 0,
                    "days_after": 2,
                },
                {
                    "id": "chongyang",
                    "name": "重阳节",
                    "emoji": "🏔️",
                    "search": "double ninth chongyang 重阳 登高 菊花 敬老",
                    "lunar_month": 9,
                    "lunar_day": 9,
                    "days_before": 0,
                    "days_after": 0,
                },
            ]
        },
        "position": 0,
    },
    {
        "key": "gen:places",
        "section": "places",
        "title": "Places",
        "icon": "map-pin",
        "color": "bg-emerald-500/5",
        "generator": "per_place",
        "generator_config": {"grid": 0.5, "radius_km": 30, "max_clusters": 50},
        "position": 0,
    },
]
